import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/mockito.dart';
import 'package:sunflower/core/api/sunflower_api.dart';
import 'package:sunflower/core/player/player_bootstrap.dart';
import 'package:sunflower/core/player/sunflower_audio_handler.dart';
import 'package:sunflower/features/library/songs_screen.dart';

// ---------------------------------------------------------------------------
// Minimal mocks — generated by mockito but hand-written here for simplicity.
// ---------------------------------------------------------------------------

class MockSunflowerApi extends Mock implements SunflowerApi {
  final List<Song> _songs;
  MockSunflowerApi(this._songs);

  @override
  Future<List<Song>> listSongs({int limit = 100, int offset = 0}) async =>
      _songs;

  @override
  String streamUrl(String mediaId) => 'http://test/$mediaId/stream';

  @override
  String artUrl(String albumId, {int size = 512}) =>
      'http://test/art/$albumId?size=$size';

  @override
  Map<String, String> get authHeaders => {'Authorization': 'Bearer test'};
}

class _FakeHandler extends Fake implements SunflowerAudioHandler {}

void main() {
  final fakeSongs = [
    const Song(
      mediaId: 'local:aabb',
      sourceType: 'local',
      title: 'Test Song 1',
      artistName: 'Artist One',
      albumTitle: 'Album Alpha',
      hasArt: false,
    ),
    const Song(
      mediaId: 'local:ccdd',
      sourceType: 'local',
      title: 'Test Song 2',
      artistName: 'Artist Two',
      albumTitle: 'Album Beta',
      hasArt: false,
    ),
  ];

  testWidgets('SongsScreen renders song titles from the API', (tester) async {
    final api = MockSunflowerApi(fakeSongs);
    final fakeHandler = _FakeHandler();

    await tester.pumpWidget(
      ProviderScope(
        overrides: [
          sunflowerApiProvider.overrideWithValue(api),
          audioHandlerProvider.overrideWithValue(fakeHandler),
        ],
        child: const MaterialApp(home: SongsScreen()),
      ),
    );

    // Wait for the FutureProvider to resolve.
    await tester.pumpAndSettle();

    expect(find.text('Test Song 1'), findsOneWidget);
    expect(find.text('Test Song 2'), findsOneWidget);
    expect(find.text('Artist One · Album Alpha'), findsOneWidget);
  });

  testWidgets('SongsScreen filters by search query', (tester) async {
    final api = MockSunflowerApi(fakeSongs);
    final fakeHandler = _FakeHandler();

    await tester.pumpWidget(
      ProviderScope(
        overrides: [
          sunflowerApiProvider.overrideWithValue(api),
          audioHandlerProvider.overrideWithValue(fakeHandler),
        ],
        child: const MaterialApp(home: SongsScreen()),
      ),
    );
    await tester.pumpAndSettle();

    // Type a query that matches only the first song.
    await tester.enterText(find.byType(TextField), 'Song 1');
    await tester.pump();

    expect(find.text('Test Song 1'), findsOneWidget);
    expect(find.text('Test Song 2'), findsNothing);
  });
}
