[workspace]
members = ["./sunflower-*",]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true      # Strip symbols from binary

[profile.dev]
opt-level = 1 # Slightly better performance in dev mode