// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -2100559637;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__append_recommendation_event_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "append_recommendation_event",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_handle = <crate::api::CoreHandle>::sse_decode(&mut deserializer);
            let api_event = <crate::api::RecommendationEventDto>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::api::append_recommendation_event(api_handle, api_event)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__empty_stats_snapshot_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "empty_stats_snapshot",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::empty_stats_snapshot())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__latest_recommendation_snapshot_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "latest_recommendation_snapshot",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_handle = <crate::api::CoreHandle>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::latest_recommendation_snapshot(api_handle)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__list_local_songs_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "list_local_songs",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_handle = <crate::api::CoreHandle>::sse_decode(&mut deserializer);
            let api_limit = <i64>::sse_decode(&mut deserializer);
            let api_offset = <i64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::api::list_local_songs(api_handle, api_limit, api_offset)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__local_candidate_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "local_candidate",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_media_id = <String>::sse_decode(&mut deserializer);
            let api_title = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::local_candidate(api_media_id, api_title))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__local_stats_snapshot_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "local_stats_snapshot",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_handle = <crate::api::CoreHandle>::sse_decode(&mut deserializer);
            let api_recent_limit = <i64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::api::local_stats_snapshot(api_handle, api_recent_limit)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__mark_recommendation_events_synced_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "mark_recommendation_events_synced",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_handle = <crate::api::CoreHandle>::sse_decode(&mut deserializer);
            let api_event_ids = <Vec<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::mark_recommendation_events_synced(
                            api_handle,
                            api_event_ids,
                        )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__new_event_id_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "new_event_id",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::new_event_id())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__open_core_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "open_core",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_config = <crate::api::CoreConfig>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::open_core(api_config)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__put_recommendation_snapshot_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "put_recommendation_snapshot",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_handle = <crate::api::CoreHandle>::sse_decode(&mut deserializer);
            let api_snapshot =
                <crate::api::RecommendationSnapshotDto>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::api::put_recommendation_snapshot(api_handle, api_snapshot)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__rank_local_candidates_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "rank_local_candidates",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_candidates =
                <Vec<crate::api::RecommendationCandidateDto>>::sse_decode(&mut deserializer);
            let api_stats = <crate::api::LocalStatsSnapshotDto>::sse_decode(&mut deserializer);
            let api_limit = <i32>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::rank_local_candidates(
                        api_candidates,
                        api_stats,
                        api_limit,
                    ))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__rank_local_from_snapshot_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "rank_local_from_snapshot",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_handle = <crate::api::CoreHandle>::sse_decode(&mut deserializer);
            let api_stats = <crate::api::LocalStatsSnapshotDto>::sse_decode(&mut deserializer);
            let api_limit = <i32>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::api::rank_local_from_snapshot(api_handle, api_stats, api_limit)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__song_from_local_file_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "song_from_local_file",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_media_id = <String>::sse_decode(&mut deserializer);
            let api_title = <String>::sse_decode(&mut deserializer);
            let api_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::song_from_local_file(
                        api_media_id,
                        api_title,
                        api_path,
                    ))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__unsynced_recommendation_events_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "unsynced_recommendation_events",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_handle = <crate::api::CoreHandle>::sse_decode(&mut deserializer);
            let api_limit = <i64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::api::unsynced_recommendation_events(api_handle, api_limit)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__upsert_local_song_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "upsert_local_song",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_handle = <crate::api::CoreHandle>::sse_decode(&mut deserializer);
            let api_song = <crate::api::SongDto>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::upsert_local_song(api_handle, api_song)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::CoreConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sqlitePath = <Option<String>>::sse_decode(deserializer);
        let mut var_recommendationServerUrl = <Option<String>>::sse_decode(deserializer);
        return crate::api::CoreConfig {
            sqlite_path: var_sqlitePath,
            recommendation_server_url: var_recommendationServerUrl,
        };
    }
}

impl SseDecode for crate::api::CoreHandle {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sqlitePath = <Option<String>>::sse_decode(deserializer);
        let mut var_recommendationServerUrl = <Option<String>>::sse_decode(deserializer);
        return crate::api::CoreHandle {
            sqlite_path: var_sqlitePath,
            recommendation_server_url: var_recommendationServerUrl,
        };
    }
}

impl SseDecode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::RecommendationCandidateDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::RecommendationCandidateDto>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::RecommendationEventDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::RecommendationEventDto>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::SongDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::SongDto>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::TrackStatsDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::TrackStatsDto>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::LocalStatsSnapshotDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_generatedAtMs = <i64>::sse_decode(deserializer);
        let mut var_tracks = <Vec<crate::api::TrackStatsDto>>::sse_decode(deserializer);
        let mut var_recentMediaIds = <Vec<String>>::sse_decode(deserializer);
        let mut var_recentArtistNames = <Vec<String>>::sse_decode(deserializer);
        return crate::api::LocalStatsSnapshotDto {
            generated_at_ms: var_generatedAtMs,
            tracks: var_tracks,
            recent_media_ids: var_recentMediaIds,
            recent_artist_names: var_recentArtistNames,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<i32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<i32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<i64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::RecommendationSnapshotDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::RecommendationSnapshotDto>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::RecommendationCandidateDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_mediaId = <String>::sse_decode(deserializer);
        let mut var_title = <String>::sse_decode(deserializer);
        let mut var_artists = <Vec<String>>::sse_decode(deserializer);
        let mut var_albumId = <Option<String>>::sse_decode(deserializer);
        let mut var_durationMs = <i32>::sse_decode(deserializer);
        let mut var_source = <crate::api::RecommendationSourceDto>::sse_decode(deserializer);
        let mut var_remoteScore = <f32>::sse_decode(deserializer);
        let mut var_reason = <Option<String>>::sse_decode(deserializer);
        return crate::api::RecommendationCandidateDto {
            media_id: var_mediaId,
            title: var_title,
            artists: var_artists,
            album_id: var_albumId,
            duration_ms: var_durationMs,
            source: var_source,
            remote_score: var_remoteScore,
            reason: var_reason,
        };
    }
}

impl SseDecode for crate::api::RecommendationEventDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_eventId = <String>::sse_decode(deserializer);
        let mut var_deviceId = <Option<String>>::sse_decode(deserializer);
        let mut var_clientClock = <i64>::sse_decode(deserializer);
        let mut var_occurredAtMs = <i64>::sse_decode(deserializer);
        let mut var_kind = <crate::api::RecommendationEventKindDto>::sse_decode(deserializer);
        let mut var_mediaId = <String>::sse_decode(deserializer);
        let mut var_queueId = <Option<String>>::sse_decode(deserializer);
        let mut var_recommenderSource =
            <crate::api::RecommendationSourceDto>::sse_decode(deserializer);
        let mut var_contextJson = <String>::sse_decode(deserializer);
        let mut var_payloadJson = <String>::sse_decode(deserializer);
        return crate::api::RecommendationEventDto {
            event_id: var_eventId,
            device_id: var_deviceId,
            client_clock: var_clientClock,
            occurred_at_ms: var_occurredAtMs,
            kind: var_kind,
            media_id: var_mediaId,
            queue_id: var_queueId,
            recommender_source: var_recommenderSource,
            context_json: var_contextJson,
            payload_json: var_payloadJson,
        };
    }
}

impl SseDecode for crate::api::RecommendationEventKindDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::RecommendationEventKindDto::Impression,
            1 => crate::api::RecommendationEventKindDto::PlayStarted,
            2 => crate::api::RecommendationEventKindDto::PlayCompleted,
            3 => crate::api::RecommendationEventKindDto::Skipped,
            4 => crate::api::RecommendationEventKindDto::Liked,
            5 => crate::api::RecommendationEventKindDto::Disliked,
            _ => unreachable!("Invalid variant for RecommendationEventKindDto: {}", inner),
        };
    }
}

impl SseDecode for crate::api::RecommendationSnapshotDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_snapshotId = <String>::sse_decode(deserializer);
        let mut var_modelVersion = <String>::sse_decode(deserializer);
        let mut var_generatedAtMs = <i64>::sse_decode(deserializer);
        let mut var_expiresAtMs = <i64>::sse_decode(deserializer);
        let mut var_candidates =
            <Vec<crate::api::RecommendationCandidateDto>>::sse_decode(deserializer);
        return crate::api::RecommendationSnapshotDto {
            snapshot_id: var_snapshotId,
            model_version: var_modelVersion,
            generated_at_ms: var_generatedAtMs,
            expires_at_ms: var_expiresAtMs,
            candidates: var_candidates,
        };
    }
}

impl SseDecode for crate::api::RecommendationSourceDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::RecommendationSourceDto::Local,
            1 => crate::api::RecommendationSourceDto::Remote,
            2 => crate::api::RecommendationSourceDto::Mixed,
            _ => unreachable!("Invalid variant for RecommendationSourceDto: {}", inner),
        };
    }
}

impl SseDecode for crate::api::SongDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_mediaId = <String>::sse_decode(deserializer);
        let mut var_sourceType = <String>::sse_decode(deserializer);
        let mut var_title = <String>::sse_decode(deserializer);
        let mut var_artists = <Vec<String>>::sse_decode(deserializer);
        let mut var_albumId = <Option<String>>::sse_decode(deserializer);
        let mut var_durationMs = <Option<i32>>::sse_decode(deserializer);
        let mut var_explicit = <bool>::sse_decode(deserializer);
        let mut var_videoOnly = <bool>::sse_decode(deserializer);
        let mut var_available = <bool>::sse_decode(deserializer);
        let mut var_localPath = <Option<String>>::sse_decode(deserializer);
        return crate::api::SongDto {
            media_id: var_mediaId,
            source_type: var_sourceType,
            title: var_title,
            artists: var_artists,
            album_id: var_albumId,
            duration_ms: var_durationMs,
            explicit: var_explicit,
            video_only: var_videoOnly,
            available: var_available,
            local_path: var_localPath,
        };
    }
}

impl SseDecode for crate::api::TrackStatsDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_mediaId = <String>::sse_decode(deserializer);
        let mut var_playCount = <i64>::sse_decode(deserializer);
        let mut var_skipCount = <i64>::sse_decode(deserializer);
        let mut var_completionCount = <i64>::sse_decode(deserializer);
        let mut var_impressionCount = <i64>::sse_decode(deserializer);
        let mut var_liked = <bool>::sse_decode(deserializer);
        let mut var_downloaded = <bool>::sse_decode(deserializer);
        let mut var_localAvailable = <bool>::sse_decode(deserializer);
        let mut var_lastPlayedAtMs = <Option<i64>>::sse_decode(deserializer);
        return crate::api::TrackStatsDto {
            media_id: var_mediaId,
            play_count: var_playCount,
            skip_count: var_skipCount,
            completion_count: var_completionCount,
            impression_count: var_impressionCount,
            liked: var_liked,
            downloaded: var_downloaded,
            local_available: var_localAvailable,
            last_played_at_ms: var_lastPlayedAtMs,
        };
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__append_recommendation_event_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__empty_stats_snapshot_impl(port, ptr, rust_vec_len, data_len),
        3 => {
            wire__crate__api__latest_recommendation_snapshot_impl(port, ptr, rust_vec_len, data_len)
        }
        4 => wire__crate__api__list_local_songs_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__api__local_candidate_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__local_stats_snapshot_impl(port, ptr, rust_vec_len, data_len),
        7 => wire__crate__api__mark_recommendation_events_synced_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        8 => wire__crate__api__new_event_id_impl(port, ptr, rust_vec_len, data_len),
        9 => wire__crate__api__open_core_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__api__put_recommendation_snapshot_impl(port, ptr, rust_vec_len, data_len),
        11 => wire__crate__api__rank_local_candidates_impl(port, ptr, rust_vec_len, data_len),
        12 => wire__crate__api__rank_local_from_snapshot_impl(port, ptr, rust_vec_len, data_len),
        13 => wire__crate__api__song_from_local_file_impl(port, ptr, rust_vec_len, data_len),
        14 => {
            wire__crate__api__unsynced_recommendation_events_impl(port, ptr, rust_vec_len, data_len)
        }
        15 => wire__crate__api__upsert_local_song_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::CoreConfig {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.sqlite_path.into_into_dart().into_dart(),
            self.recommendation_server_url.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::CoreConfig {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::CoreConfig> for crate::api::CoreConfig {
    fn into_into_dart(self) -> crate::api::CoreConfig {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::CoreHandle {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.sqlite_path.into_into_dart().into_dart(),
            self.recommendation_server_url.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::CoreHandle {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::CoreHandle> for crate::api::CoreHandle {
    fn into_into_dart(self) -> crate::api::CoreHandle {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::LocalStatsSnapshotDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.generated_at_ms.into_into_dart().into_dart(),
            self.tracks.into_into_dart().into_dart(),
            self.recent_media_ids.into_into_dart().into_dart(),
            self.recent_artist_names.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::LocalStatsSnapshotDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::LocalStatsSnapshotDto>
    for crate::api::LocalStatsSnapshotDto
{
    fn into_into_dart(self) -> crate::api::LocalStatsSnapshotDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::RecommendationCandidateDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.media_id.into_into_dart().into_dart(),
            self.title.into_into_dart().into_dart(),
            self.artists.into_into_dart().into_dart(),
            self.album_id.into_into_dart().into_dart(),
            self.duration_ms.into_into_dart().into_dart(),
            self.source.into_into_dart().into_dart(),
            self.remote_score.into_into_dart().into_dart(),
            self.reason.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::RecommendationCandidateDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::RecommendationCandidateDto>
    for crate::api::RecommendationCandidateDto
{
    fn into_into_dart(self) -> crate::api::RecommendationCandidateDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::RecommendationEventDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.event_id.into_into_dart().into_dart(),
            self.device_id.into_into_dart().into_dart(),
            self.client_clock.into_into_dart().into_dart(),
            self.occurred_at_ms.into_into_dart().into_dart(),
            self.kind.into_into_dart().into_dart(),
            self.media_id.into_into_dart().into_dart(),
            self.queue_id.into_into_dart().into_dart(),
            self.recommender_source.into_into_dart().into_dart(),
            self.context_json.into_into_dart().into_dart(),
            self.payload_json.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::RecommendationEventDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::RecommendationEventDto>
    for crate::api::RecommendationEventDto
{
    fn into_into_dart(self) -> crate::api::RecommendationEventDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::RecommendationEventKindDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Impression => 0.into_dart(),
            Self::PlayStarted => 1.into_dart(),
            Self::PlayCompleted => 2.into_dart(),
            Self::Skipped => 3.into_dart(),
            Self::Liked => 4.into_dart(),
            Self::Disliked => 5.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::RecommendationEventKindDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::RecommendationEventKindDto>
    for crate::api::RecommendationEventKindDto
{
    fn into_into_dart(self) -> crate::api::RecommendationEventKindDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::RecommendationSnapshotDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.snapshot_id.into_into_dart().into_dart(),
            self.model_version.into_into_dart().into_dart(),
            self.generated_at_ms.into_into_dart().into_dart(),
            self.expires_at_ms.into_into_dart().into_dart(),
            self.candidates.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::RecommendationSnapshotDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::RecommendationSnapshotDto>
    for crate::api::RecommendationSnapshotDto
{
    fn into_into_dart(self) -> crate::api::RecommendationSnapshotDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::RecommendationSourceDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Local => 0.into_dart(),
            Self::Remote => 1.into_dart(),
            Self::Mixed => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::RecommendationSourceDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::RecommendationSourceDto>
    for crate::api::RecommendationSourceDto
{
    fn into_into_dart(self) -> crate::api::RecommendationSourceDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::SongDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.media_id.into_into_dart().into_dart(),
            self.source_type.into_into_dart().into_dart(),
            self.title.into_into_dart().into_dart(),
            self.artists.into_into_dart().into_dart(),
            self.album_id.into_into_dart().into_dart(),
            self.duration_ms.into_into_dart().into_dart(),
            self.explicit.into_into_dart().into_dart(),
            self.video_only.into_into_dart().into_dart(),
            self.available.into_into_dart().into_dart(),
            self.local_path.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::SongDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::SongDto> for crate::api::SongDto {
    fn into_into_dart(self) -> crate::api::SongDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::TrackStatsDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.media_id.into_into_dart().into_dart(),
            self.play_count.into_into_dart().into_dart(),
            self.skip_count.into_into_dart().into_dart(),
            self.completion_count.into_into_dart().into_dart(),
            self.impression_count.into_into_dart().into_dart(),
            self.liked.into_into_dart().into_dart(),
            self.downloaded.into_into_dart().into_dart(),
            self.local_available.into_into_dart().into_dart(),
            self.last_played_at_ms.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::TrackStatsDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::TrackStatsDto> for crate::api::TrackStatsDto {
    fn into_into_dart(self) -> crate::api::TrackStatsDto {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::CoreConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<String>>::sse_encode(self.sqlite_path, serializer);
        <Option<String>>::sse_encode(self.recommendation_server_url, serializer);
    }
}

impl SseEncode for crate::api::CoreHandle {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<String>>::sse_encode(self.sqlite_path, serializer);
        <Option<String>>::sse_encode(self.recommendation_server_url, serializer);
    }
}

impl SseEncode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::RecommendationCandidateDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::RecommendationCandidateDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::RecommendationEventDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::RecommendationEventDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::SongDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::SongDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::TrackStatsDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::TrackStatsDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::LocalStatsSnapshotDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.generated_at_ms, serializer);
        <Vec<crate::api::TrackStatsDto>>::sse_encode(self.tracks, serializer);
        <Vec<String>>::sse_encode(self.recent_media_ids, serializer);
        <Vec<String>>::sse_encode(self.recent_artist_names, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<i32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <i32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <i64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::RecommendationSnapshotDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::RecommendationSnapshotDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::RecommendationCandidateDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.media_id, serializer);
        <String>::sse_encode(self.title, serializer);
        <Vec<String>>::sse_encode(self.artists, serializer);
        <Option<String>>::sse_encode(self.album_id, serializer);
        <i32>::sse_encode(self.duration_ms, serializer);
        <crate::api::RecommendationSourceDto>::sse_encode(self.source, serializer);
        <f32>::sse_encode(self.remote_score, serializer);
        <Option<String>>::sse_encode(self.reason, serializer);
    }
}

impl SseEncode for crate::api::RecommendationEventDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.event_id, serializer);
        <Option<String>>::sse_encode(self.device_id, serializer);
        <i64>::sse_encode(self.client_clock, serializer);
        <i64>::sse_encode(self.occurred_at_ms, serializer);
        <crate::api::RecommendationEventKindDto>::sse_encode(self.kind, serializer);
        <String>::sse_encode(self.media_id, serializer);
        <Option<String>>::sse_encode(self.queue_id, serializer);
        <crate::api::RecommendationSourceDto>::sse_encode(self.recommender_source, serializer);
        <String>::sse_encode(self.context_json, serializer);
        <String>::sse_encode(self.payload_json, serializer);
    }
}

impl SseEncode for crate::api::RecommendationEventKindDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::RecommendationEventKindDto::Impression => 0,
                crate::api::RecommendationEventKindDto::PlayStarted => 1,
                crate::api::RecommendationEventKindDto::PlayCompleted => 2,
                crate::api::RecommendationEventKindDto::Skipped => 3,
                crate::api::RecommendationEventKindDto::Liked => 4,
                crate::api::RecommendationEventKindDto::Disliked => 5,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::RecommendationSnapshotDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.snapshot_id, serializer);
        <String>::sse_encode(self.model_version, serializer);
        <i64>::sse_encode(self.generated_at_ms, serializer);
        <i64>::sse_encode(self.expires_at_ms, serializer);
        <Vec<crate::api::RecommendationCandidateDto>>::sse_encode(self.candidates, serializer);
    }
}

impl SseEncode for crate::api::RecommendationSourceDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::RecommendationSourceDto::Local => 0,
                crate::api::RecommendationSourceDto::Remote => 1,
                crate::api::RecommendationSourceDto::Mixed => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::SongDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.media_id, serializer);
        <String>::sse_encode(self.source_type, serializer);
        <String>::sse_encode(self.title, serializer);
        <Vec<String>>::sse_encode(self.artists, serializer);
        <Option<String>>::sse_encode(self.album_id, serializer);
        <Option<i32>>::sse_encode(self.duration_ms, serializer);
        <bool>::sse_encode(self.explicit, serializer);
        <bool>::sse_encode(self.video_only, serializer);
        <bool>::sse_encode(self.available, serializer);
        <Option<String>>::sse_encode(self.local_path, serializer);
    }
}

impl SseEncode for crate::api::TrackStatsDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.media_id, serializer);
        <i64>::sse_encode(self.play_count, serializer);
        <i64>::sse_encode(self.skip_count, serializer);
        <i64>::sse_encode(self.completion_count, serializer);
        <i64>::sse_encode(self.impression_count, serializer);
        <bool>::sse_encode(self.liked, serializer);
        <bool>::sse_encode(self.downloaded, serializer);
        <bool>::sse_encode(self.local_available, serializer);
        <Option<i64>>::sse_encode(self.last_played_at_ms, serializer);
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
