// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `event_from_dto`, `event_to_dto`, `local_candidate_from_song`, `millis_to_utc`, `parse_json_object`, `parse_optional_uuid`, `snapshot_from_dto`, `snapshot_to_dto`, `store_for_handle`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

Future<CoreHandle> openCore({required CoreConfig config}) =>
    RustLib.instance.api.crateApiOpenCore(config: config);

Future<String> newEventId() => RustLib.instance.api.crateApiNewEventId();

Future<void> upsertLocalSong(
        {required CoreHandle handle, required SongDto song}) =>
    RustLib.instance.api.crateApiUpsertLocalSong(handle: handle, song: song);

Future<List<SongDto>> listLocalSongs(
        {required CoreHandle handle,
        required PlatformInt64 limit,
        required PlatformInt64 offset}) =>
    RustLib.instance.api
        .crateApiListLocalSongs(handle: handle, limit: limit, offset: offset);

Future<void> appendRecommendationEvent(
        {required CoreHandle handle, required RecommendationEventDto event}) =>
    RustLib.instance.api
        .crateApiAppendRecommendationEvent(handle: handle, event: event);

Future<List<RecommendationEventDto>> unsyncedRecommendationEvents(
        {required CoreHandle handle, required PlatformInt64 limit}) =>
    RustLib.instance.api
        .crateApiUnsyncedRecommendationEvents(handle: handle, limit: limit);

Future<void> markRecommendationEventsSynced(
        {required CoreHandle handle, required List<String> eventIds}) =>
    RustLib.instance.api.crateApiMarkRecommendationEventsSynced(
        handle: handle, eventIds: eventIds);

Future<void> putRecommendationSnapshot(
        {required CoreHandle handle,
        required RecommendationSnapshotDto snapshot}) =>
    RustLib.instance.api
        .crateApiPutRecommendationSnapshot(handle: handle, snapshot: snapshot);

Future<RecommendationSnapshotDto?> latestRecommendationSnapshot(
        {required CoreHandle handle}) =>
    RustLib.instance.api.crateApiLatestRecommendationSnapshot(handle: handle);

Future<LocalStatsSnapshotDto> localStatsSnapshot(
        {required CoreHandle handle, required PlatformInt64 recentLimit}) =>
    RustLib.instance.api
        .crateApiLocalStatsSnapshot(handle: handle, recentLimit: recentLimit);

Future<List<RecommendationCandidateDto>> rankLocalFromSnapshot(
        {required CoreHandle handle,
        required LocalStatsSnapshotDto stats,
        required int limit}) =>
    RustLib.instance.api.crateApiRankLocalFromSnapshot(
        handle: handle, stats: stats, limit: limit);

Future<List<RecommendationCandidateDto>> rankLocalCandidates(
        {required List<RecommendationCandidateDto> candidates,
        required LocalStatsSnapshotDto stats,
        required int limit}) =>
    RustLib.instance.api.crateApiRankLocalCandidates(
        candidates: candidates, stats: stats, limit: limit);

Future<LocalStatsSnapshotDto> emptyStatsSnapshot() =>
    RustLib.instance.api.crateApiEmptyStatsSnapshot();

Future<SongDto> songFromLocalFile(
        {required String mediaId,
        required String title,
        required String path}) =>
    RustLib.instance.api
        .crateApiSongFromLocalFile(mediaId: mediaId, title: title, path: path);

Future<RecommendationCandidateDto> localCandidate(
        {required String mediaId, required String title}) =>
    RustLib.instance.api.crateApiLocalCandidate(mediaId: mediaId, title: title);

class CoreConfig {
  final String? sqlitePath;
  final String? recommendationServerUrl;

  const CoreConfig({
    this.sqlitePath,
    this.recommendationServerUrl,
  });

  @override
  int get hashCode => sqlitePath.hashCode ^ recommendationServerUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreConfig &&
          runtimeType == other.runtimeType &&
          sqlitePath == other.sqlitePath &&
          recommendationServerUrl == other.recommendationServerUrl;
}

class CoreHandle {
  final String? sqlitePath;
  final String? recommendationServerUrl;

  const CoreHandle({
    this.sqlitePath,
    this.recommendationServerUrl,
  });

  @override
  int get hashCode => sqlitePath.hashCode ^ recommendationServerUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreHandle &&
          runtimeType == other.runtimeType &&
          sqlitePath == other.sqlitePath &&
          recommendationServerUrl == other.recommendationServerUrl;
}

class LocalStatsSnapshotDto {
  final PlatformInt64 generatedAtMs;
  final List<TrackStatsDto> tracks;
  final List<String> recentMediaIds;
  final List<String> recentArtistNames;

  const LocalStatsSnapshotDto({
    required this.generatedAtMs,
    required this.tracks,
    required this.recentMediaIds,
    required this.recentArtistNames,
  });

  @override
  int get hashCode =>
      generatedAtMs.hashCode ^
      tracks.hashCode ^
      recentMediaIds.hashCode ^
      recentArtistNames.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalStatsSnapshotDto &&
          runtimeType == other.runtimeType &&
          generatedAtMs == other.generatedAtMs &&
          tracks == other.tracks &&
          recentMediaIds == other.recentMediaIds &&
          recentArtistNames == other.recentArtistNames;
}

class RecommendationCandidateDto {
  final String mediaId;
  final String title;
  final List<String> artists;
  final String? albumId;
  final int durationMs;
  final RecommendationSourceDto source;
  final double remoteScore;
  final String? reason;

  const RecommendationCandidateDto({
    required this.mediaId,
    required this.title,
    required this.artists,
    this.albumId,
    required this.durationMs,
    required this.source,
    required this.remoteScore,
    this.reason,
  });

  @override
  int get hashCode =>
      mediaId.hashCode ^
      title.hashCode ^
      artists.hashCode ^
      albumId.hashCode ^
      durationMs.hashCode ^
      source.hashCode ^
      remoteScore.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecommendationCandidateDto &&
          runtimeType == other.runtimeType &&
          mediaId == other.mediaId &&
          title == other.title &&
          artists == other.artists &&
          albumId == other.albumId &&
          durationMs == other.durationMs &&
          source == other.source &&
          remoteScore == other.remoteScore &&
          reason == other.reason;
}

class RecommendationEventDto {
  final String eventId;
  final String? deviceId;
  final PlatformInt64 clientClock;
  final PlatformInt64 occurredAtMs;
  final RecommendationEventKindDto kind;
  final String mediaId;
  final String? queueId;
  final RecommendationSourceDto recommenderSource;
  final String contextJson;
  final String payloadJson;

  const RecommendationEventDto({
    required this.eventId,
    this.deviceId,
    required this.clientClock,
    required this.occurredAtMs,
    required this.kind,
    required this.mediaId,
    this.queueId,
    required this.recommenderSource,
    required this.contextJson,
    required this.payloadJson,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^
      deviceId.hashCode ^
      clientClock.hashCode ^
      occurredAtMs.hashCode ^
      kind.hashCode ^
      mediaId.hashCode ^
      queueId.hashCode ^
      recommenderSource.hashCode ^
      contextJson.hashCode ^
      payloadJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecommendationEventDto &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          deviceId == other.deviceId &&
          clientClock == other.clientClock &&
          occurredAtMs == other.occurredAtMs &&
          kind == other.kind &&
          mediaId == other.mediaId &&
          queueId == other.queueId &&
          recommenderSource == other.recommenderSource &&
          contextJson == other.contextJson &&
          payloadJson == other.payloadJson;
}

enum RecommendationEventKindDto {
  impression,
  playStarted,
  playCompleted,
  skipped,
  liked,
  disliked,
  ;
}

class RecommendationSnapshotDto {
  final String snapshotId;
  final String modelVersion;
  final PlatformInt64 generatedAtMs;
  final PlatformInt64 expiresAtMs;
  final List<RecommendationCandidateDto> candidates;

  const RecommendationSnapshotDto({
    required this.snapshotId,
    required this.modelVersion,
    required this.generatedAtMs,
    required this.expiresAtMs,
    required this.candidates,
  });

  @override
  int get hashCode =>
      snapshotId.hashCode ^
      modelVersion.hashCode ^
      generatedAtMs.hashCode ^
      expiresAtMs.hashCode ^
      candidates.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecommendationSnapshotDto &&
          runtimeType == other.runtimeType &&
          snapshotId == other.snapshotId &&
          modelVersion == other.modelVersion &&
          generatedAtMs == other.generatedAtMs &&
          expiresAtMs == other.expiresAtMs &&
          candidates == other.candidates;
}

enum RecommendationSourceDto {
  local,
  remote,
  mixed,
  ;
}

class SongDto {
  final String mediaId;
  final String sourceType;
  final String title;
  final List<String> artists;
  final String? albumId;
  final int? durationMs;
  final bool explicit;
  final bool videoOnly;
  final bool available;
  final String? localPath;

  const SongDto({
    required this.mediaId,
    required this.sourceType,
    required this.title,
    required this.artists,
    this.albumId,
    this.durationMs,
    required this.explicit,
    required this.videoOnly,
    required this.available,
    this.localPath,
  });

  @override
  int get hashCode =>
      mediaId.hashCode ^
      sourceType.hashCode ^
      title.hashCode ^
      artists.hashCode ^
      albumId.hashCode ^
      durationMs.hashCode ^
      explicit.hashCode ^
      videoOnly.hashCode ^
      available.hashCode ^
      localPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SongDto &&
          runtimeType == other.runtimeType &&
          mediaId == other.mediaId &&
          sourceType == other.sourceType &&
          title == other.title &&
          artists == other.artists &&
          albumId == other.albumId &&
          durationMs == other.durationMs &&
          explicit == other.explicit &&
          videoOnly == other.videoOnly &&
          available == other.available &&
          localPath == other.localPath;
}

class TrackStatsDto {
  final String mediaId;
  final PlatformInt64 playCount;
  final PlatformInt64 skipCount;
  final PlatformInt64 completionCount;
  final PlatformInt64 impressionCount;
  final bool liked;
  final bool downloaded;
  final bool localAvailable;
  final PlatformInt64? lastPlayedAtMs;

  const TrackStatsDto({
    required this.mediaId,
    required this.playCount,
    required this.skipCount,
    required this.completionCount,
    required this.impressionCount,
    required this.liked,
    required this.downloaded,
    required this.localAvailable,
    this.lastPlayedAtMs,
  });

  @override
  int get hashCode =>
      mediaId.hashCode ^
      playCount.hashCode ^
      skipCount.hashCode ^
      completionCount.hashCode ^
      impressionCount.hashCode ^
      liked.hashCode ^
      downloaded.hashCode ^
      localAvailable.hashCode ^
      lastPlayedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackStatsDto &&
          runtimeType == other.runtimeType &&
          mediaId == other.mediaId &&
          playCount == other.playCount &&
          skipCount == other.skipCount &&
          completionCount == other.completionCount &&
          impressionCount == other.impressionCount &&
          liked == other.liked &&
          downloaded == other.downloaded &&
          localAvailable == other.localAvailable &&
          lastPlayedAtMs == other.lastPlayedAtMs;
}
