// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CoreConfig dco_decode_box_autoadd_core_config(dynamic raw);

  @protected
  CoreHandle dco_decode_box_autoadd_core_handle(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  LocalStatsSnapshotDto dco_decode_box_autoadd_local_stats_snapshot_dto(
      dynamic raw);

  @protected
  RecommendationEventDto dco_decode_box_autoadd_recommendation_event_dto(
      dynamic raw);

  @protected
  RecommendationSnapshotDto dco_decode_box_autoadd_recommendation_snapshot_dto(
      dynamic raw);

  @protected
  SongDto dco_decode_box_autoadd_song_dto(dynamic raw);

  @protected
  CoreConfig dco_decode_core_config(dynamic raw);

  @protected
  CoreHandle dco_decode_core_handle(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RecommendationCandidateDto> dco_decode_list_recommendation_candidate_dto(
      dynamic raw);

  @protected
  List<RecommendationEventDto> dco_decode_list_recommendation_event_dto(
      dynamic raw);

  @protected
  List<SongDto> dco_decode_list_song_dto(dynamic raw);

  @protected
  List<TrackStatsDto> dco_decode_list_track_stats_dto(dynamic raw);

  @protected
  LocalStatsSnapshotDto dco_decode_local_stats_snapshot_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  RecommendationSnapshotDto?
      dco_decode_opt_box_autoadd_recommendation_snapshot_dto(dynamic raw);

  @protected
  RecommendationCandidateDto dco_decode_recommendation_candidate_dto(
      dynamic raw);

  @protected
  RecommendationEventDto dco_decode_recommendation_event_dto(dynamic raw);

  @protected
  RecommendationEventKindDto dco_decode_recommendation_event_kind_dto(
      dynamic raw);

  @protected
  RecommendationSnapshotDto dco_decode_recommendation_snapshot_dto(dynamic raw);

  @protected
  RecommendationSourceDto dco_decode_recommendation_source_dto(dynamic raw);

  @protected
  SongDto dco_decode_song_dto(dynamic raw);

  @protected
  TrackStatsDto dco_decode_track_stats_dto(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CoreConfig sse_decode_box_autoadd_core_config(SseDeserializer deserializer);

  @protected
  CoreHandle sse_decode_box_autoadd_core_handle(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  LocalStatsSnapshotDto sse_decode_box_autoadd_local_stats_snapshot_dto(
      SseDeserializer deserializer);

  @protected
  RecommendationEventDto sse_decode_box_autoadd_recommendation_event_dto(
      SseDeserializer deserializer);

  @protected
  RecommendationSnapshotDto sse_decode_box_autoadd_recommendation_snapshot_dto(
      SseDeserializer deserializer);

  @protected
  SongDto sse_decode_box_autoadd_song_dto(SseDeserializer deserializer);

  @protected
  CoreConfig sse_decode_core_config(SseDeserializer deserializer);

  @protected
  CoreHandle sse_decode_core_handle(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RecommendationCandidateDto> sse_decode_list_recommendation_candidate_dto(
      SseDeserializer deserializer);

  @protected
  List<RecommendationEventDto> sse_decode_list_recommendation_event_dto(
      SseDeserializer deserializer);

  @protected
  List<SongDto> sse_decode_list_song_dto(SseDeserializer deserializer);

  @protected
  List<TrackStatsDto> sse_decode_list_track_stats_dto(
      SseDeserializer deserializer);

  @protected
  LocalStatsSnapshotDto sse_decode_local_stats_snapshot_dto(
      SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  RecommendationSnapshotDto?
      sse_decode_opt_box_autoadd_recommendation_snapshot_dto(
          SseDeserializer deserializer);

  @protected
  RecommendationCandidateDto sse_decode_recommendation_candidate_dto(
      SseDeserializer deserializer);

  @protected
  RecommendationEventDto sse_decode_recommendation_event_dto(
      SseDeserializer deserializer);

  @protected
  RecommendationEventKindDto sse_decode_recommendation_event_kind_dto(
      SseDeserializer deserializer);

  @protected
  RecommendationSnapshotDto sse_decode_recommendation_snapshot_dto(
      SseDeserializer deserializer);

  @protected
  RecommendationSourceDto sse_decode_recommendation_source_dto(
      SseDeserializer deserializer);

  @protected
  SongDto sse_decode_song_dto(SseDeserializer deserializer);

  @protected
  TrackStatsDto sse_decode_track_stats_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_core_config(
      CoreConfig self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_core_handle(
      CoreHandle self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_local_stats_snapshot_dto(
      LocalStatsSnapshotDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_recommendation_event_dto(
      RecommendationEventDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_recommendation_snapshot_dto(
      RecommendationSnapshotDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_song_dto(SongDto self, SseSerializer serializer);

  @protected
  void sse_encode_core_config(CoreConfig self, SseSerializer serializer);

  @protected
  void sse_encode_core_handle(CoreHandle self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_recommendation_candidate_dto(
      List<RecommendationCandidateDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_recommendation_event_dto(
      List<RecommendationEventDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_song_dto(List<SongDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_track_stats_dto(
      List<TrackStatsDto> self, SseSerializer serializer);

  @protected
  void sse_encode_local_stats_snapshot_dto(
      LocalStatsSnapshotDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_recommendation_snapshot_dto(
      RecommendationSnapshotDto? self, SseSerializer serializer);

  @protected
  void sse_encode_recommendation_candidate_dto(
      RecommendationCandidateDto self, SseSerializer serializer);

  @protected
  void sse_encode_recommendation_event_dto(
      RecommendationEventDto self, SseSerializer serializer);

  @protected
  void sse_encode_recommendation_event_kind_dto(
      RecommendationEventKindDto self, SseSerializer serializer);

  @protected
  void sse_encode_recommendation_snapshot_dto(
      RecommendationSnapshotDto self, SseSerializer serializer);

  @protected
  void sse_encode_recommendation_source_dto(
      RecommendationSourceDto self, SseSerializer serializer);

  @protected
  void sse_encode_song_dto(SongDto self, SseSerializer serializer);

  @protected
  void sse_encode_track_stats_dto(TrackStatsDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
