// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -2100559637;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'sunflower_bridge',
    ioDirectory: '../rust/crates/sunflower-bridge/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiAppendRecommendationEvent(
      {required CoreHandle handle, required RecommendationEventDto event});

  Future<LocalStatsSnapshotDto> crateApiEmptyStatsSnapshot();

  Future<RecommendationSnapshotDto?> crateApiLatestRecommendationSnapshot(
      {required CoreHandle handle});

  Future<List<SongDto>> crateApiListLocalSongs(
      {required CoreHandle handle,
      required PlatformInt64 limit,
      required PlatformInt64 offset});

  Future<RecommendationCandidateDto> crateApiLocalCandidate(
      {required String mediaId, required String title});

  Future<LocalStatsSnapshotDto> crateApiLocalStatsSnapshot(
      {required CoreHandle handle, required PlatformInt64 recentLimit});

  Future<void> crateApiMarkRecommendationEventsSynced(
      {required CoreHandle handle, required List<String> eventIds});

  Future<String> crateApiNewEventId();

  Future<CoreHandle> crateApiOpenCore({required CoreConfig config});

  Future<void> crateApiPutRecommendationSnapshot(
      {required CoreHandle handle,
      required RecommendationSnapshotDto snapshot});

  Future<List<RecommendationCandidateDto>> crateApiRankLocalCandidates(
      {required List<RecommendationCandidateDto> candidates,
      required LocalStatsSnapshotDto stats,
      required int limit});

  Future<List<RecommendationCandidateDto>> crateApiRankLocalFromSnapshot(
      {required CoreHandle handle,
      required LocalStatsSnapshotDto stats,
      required int limit});

  Future<SongDto> crateApiSongFromLocalFile(
      {required String mediaId, required String title, required String path});

  Future<List<RecommendationEventDto>> crateApiUnsyncedRecommendationEvents(
      {required CoreHandle handle, required PlatformInt64 limit});

  Future<void> crateApiUpsertLocalSong(
      {required CoreHandle handle, required SongDto song});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiAppendRecommendationEvent(
      {required CoreHandle handle, required RecommendationEventDto event}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_core_handle(handle, serializer);
        sse_encode_box_autoadd_recommendation_event_dto(event, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiAppendRecommendationEventConstMeta,
      argValues: [handle, event],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAppendRecommendationEventConstMeta =>
      const TaskConstMeta(
        debugName: "append_recommendation_event",
        argNames: ["handle", "event"],
      );

  @override
  Future<LocalStatsSnapshotDto> crateApiEmptyStatsSnapshot() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_local_stats_snapshot_dto,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiEmptyStatsSnapshotConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEmptyStatsSnapshotConstMeta => const TaskConstMeta(
        debugName: "empty_stats_snapshot",
        argNames: [],
      );

  @override
  Future<RecommendationSnapshotDto?> crateApiLatestRecommendationSnapshot(
      {required CoreHandle handle}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_core_handle(handle, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_opt_box_autoadd_recommendation_snapshot_dto,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiLatestRecommendationSnapshotConstMeta,
      argValues: [handle],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLatestRecommendationSnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "latest_recommendation_snapshot",
        argNames: ["handle"],
      );

  @override
  Future<List<SongDto>> crateApiListLocalSongs(
      {required CoreHandle handle,
      required PlatformInt64 limit,
      required PlatformInt64 offset}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_core_handle(handle, serializer);
        sse_encode_i_64(limit, serializer);
        sse_encode_i_64(offset, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_song_dto,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiListLocalSongsConstMeta,
      argValues: [handle, limit, offset],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiListLocalSongsConstMeta => const TaskConstMeta(
        debugName: "list_local_songs",
        argNames: ["handle", "limit", "offset"],
      );

  @override
  Future<RecommendationCandidateDto> crateApiLocalCandidate(
      {required String mediaId, required String title}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(mediaId, serializer);
        sse_encode_String(title, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_recommendation_candidate_dto,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLocalCandidateConstMeta,
      argValues: [mediaId, title],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLocalCandidateConstMeta => const TaskConstMeta(
        debugName: "local_candidate",
        argNames: ["mediaId", "title"],
      );

  @override
  Future<LocalStatsSnapshotDto> crateApiLocalStatsSnapshot(
      {required CoreHandle handle, required PlatformInt64 recentLimit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_core_handle(handle, serializer);
        sse_encode_i_64(recentLimit, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_local_stats_snapshot_dto,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiLocalStatsSnapshotConstMeta,
      argValues: [handle, recentLimit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLocalStatsSnapshotConstMeta => const TaskConstMeta(
        debugName: "local_stats_snapshot",
        argNames: ["handle", "recentLimit"],
      );

  @override
  Future<void> crateApiMarkRecommendationEventsSynced(
      {required CoreHandle handle, required List<String> eventIds}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_core_handle(handle, serializer);
        sse_encode_list_String(eventIds, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMarkRecommendationEventsSyncedConstMeta,
      argValues: [handle, eventIds],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMarkRecommendationEventsSyncedConstMeta =>
      const TaskConstMeta(
        debugName: "mark_recommendation_events_synced",
        argNames: ["handle", "eventIds"],
      );

  @override
  Future<String> crateApiNewEventId() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiNewEventIdConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNewEventIdConstMeta => const TaskConstMeta(
        debugName: "new_event_id",
        argNames: [],
      );

  @override
  Future<CoreHandle> crateApiOpenCore({required CoreConfig config}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_core_config(config, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_core_handle,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiOpenCoreConstMeta,
      argValues: [config],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOpenCoreConstMeta => const TaskConstMeta(
        debugName: "open_core",
        argNames: ["config"],
      );

  @override
  Future<void> crateApiPutRecommendationSnapshot(
      {required CoreHandle handle,
      required RecommendationSnapshotDto snapshot}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_core_handle(handle, serializer);
        sse_encode_box_autoadd_recommendation_snapshot_dto(
            snapshot, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPutRecommendationSnapshotConstMeta,
      argValues: [handle, snapshot],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPutRecommendationSnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "put_recommendation_snapshot",
        argNames: ["handle", "snapshot"],
      );

  @override
  Future<List<RecommendationCandidateDto>> crateApiRankLocalCandidates(
      {required List<RecommendationCandidateDto> candidates,
      required LocalStatsSnapshotDto stats,
      required int limit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_recommendation_candidate_dto(candidates, serializer);
        sse_encode_box_autoadd_local_stats_snapshot_dto(stats, serializer);
        sse_encode_i_32(limit, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_recommendation_candidate_dto,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiRankLocalCandidatesConstMeta,
      argValues: [candidates, stats, limit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRankLocalCandidatesConstMeta =>
      const TaskConstMeta(
        debugName: "rank_local_candidates",
        argNames: ["candidates", "stats", "limit"],
      );

  @override
  Future<List<RecommendationCandidateDto>> crateApiRankLocalFromSnapshot(
      {required CoreHandle handle,
      required LocalStatsSnapshotDto stats,
      required int limit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_core_handle(handle, serializer);
        sse_encode_box_autoadd_local_stats_snapshot_dto(stats, serializer);
        sse_encode_i_32(limit, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_recommendation_candidate_dto,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiRankLocalFromSnapshotConstMeta,
      argValues: [handle, stats, limit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRankLocalFromSnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "rank_local_from_snapshot",
        argNames: ["handle", "stats", "limit"],
      );

  @override
  Future<SongDto> crateApiSongFromLocalFile(
      {required String mediaId, required String title, required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(mediaId, serializer);
        sse_encode_String(title, serializer);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_song_dto,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSongFromLocalFileConstMeta,
      argValues: [mediaId, title, path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSongFromLocalFileConstMeta => const TaskConstMeta(
        debugName: "song_from_local_file",
        argNames: ["mediaId", "title", "path"],
      );

  @override
  Future<List<RecommendationEventDto>> crateApiUnsyncedRecommendationEvents(
      {required CoreHandle handle, required PlatformInt64 limit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_core_handle(handle, serializer);
        sse_encode_i_64(limit, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_recommendation_event_dto,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiUnsyncedRecommendationEventsConstMeta,
      argValues: [handle, limit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiUnsyncedRecommendationEventsConstMeta =>
      const TaskConstMeta(
        debugName: "unsynced_recommendation_events",
        argNames: ["handle", "limit"],
      );

  @override
  Future<void> crateApiUpsertLocalSong(
      {required CoreHandle handle, required SongDto song}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_core_handle(handle, serializer);
        sse_encode_box_autoadd_song_dto(song, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiUpsertLocalSongConstMeta,
      argValues: [handle, song],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiUpsertLocalSongConstMeta => const TaskConstMeta(
        debugName: "upsert_local_song",
        argNames: ["handle", "song"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  CoreConfig dco_decode_box_autoadd_core_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_core_config(raw);
  }

  @protected
  CoreHandle dco_decode_box_autoadd_core_handle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_core_handle(raw);
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  LocalStatsSnapshotDto dco_decode_box_autoadd_local_stats_snapshot_dto(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_local_stats_snapshot_dto(raw);
  }

  @protected
  RecommendationEventDto dco_decode_box_autoadd_recommendation_event_dto(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_recommendation_event_dto(raw);
  }

  @protected
  RecommendationSnapshotDto dco_decode_box_autoadd_recommendation_snapshot_dto(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_recommendation_snapshot_dto(raw);
  }

  @protected
  SongDto dco_decode_box_autoadd_song_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_song_dto(raw);
  }

  @protected
  CoreConfig dco_decode_core_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CoreConfig(
      sqlitePath: dco_decode_opt_String(arr[0]),
      recommendationServerUrl: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  CoreHandle dco_decode_core_handle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CoreHandle(
      sqlitePath: dco_decode_opt_String(arr[0]),
      recommendationServerUrl: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RecommendationCandidateDto> dco_decode_list_recommendation_candidate_dto(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_recommendation_candidate_dto)
        .toList();
  }

  @protected
  List<RecommendationEventDto> dco_decode_list_recommendation_event_dto(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_recommendation_event_dto)
        .toList();
  }

  @protected
  List<SongDto> dco_decode_list_song_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_song_dto).toList();
  }

  @protected
  List<TrackStatsDto> dco_decode_list_track_stats_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_track_stats_dto).toList();
  }

  @protected
  LocalStatsSnapshotDto dco_decode_local_stats_snapshot_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return LocalStatsSnapshotDto(
      generatedAtMs: dco_decode_i_64(arr[0]),
      tracks: dco_decode_list_track_stats_dto(arr[1]),
      recentMediaIds: dco_decode_list_String(arr[2]),
      recentArtistNames: dco_decode_list_String(arr[3]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  RecommendationSnapshotDto?
      dco_decode_opt_box_autoadd_recommendation_snapshot_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_recommendation_snapshot_dto(raw);
  }

  @protected
  RecommendationCandidateDto dco_decode_recommendation_candidate_dto(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return RecommendationCandidateDto(
      mediaId: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      artists: dco_decode_list_String(arr[2]),
      albumId: dco_decode_opt_String(arr[3]),
      durationMs: dco_decode_i_32(arr[4]),
      source: dco_decode_recommendation_source_dto(arr[5]),
      remoteScore: dco_decode_f_32(arr[6]),
      reason: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  RecommendationEventDto dco_decode_recommendation_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return RecommendationEventDto(
      eventId: dco_decode_String(arr[0]),
      deviceId: dco_decode_opt_String(arr[1]),
      clientClock: dco_decode_i_64(arr[2]),
      occurredAtMs: dco_decode_i_64(arr[3]),
      kind: dco_decode_recommendation_event_kind_dto(arr[4]),
      mediaId: dco_decode_String(arr[5]),
      queueId: dco_decode_opt_String(arr[6]),
      recommenderSource: dco_decode_recommendation_source_dto(arr[7]),
      contextJson: dco_decode_String(arr[8]),
      payloadJson: dco_decode_String(arr[9]),
    );
  }

  @protected
  RecommendationEventKindDto dco_decode_recommendation_event_kind_dto(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RecommendationEventKindDto.values[raw as int];
  }

  @protected
  RecommendationSnapshotDto dco_decode_recommendation_snapshot_dto(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return RecommendationSnapshotDto(
      snapshotId: dco_decode_String(arr[0]),
      modelVersion: dco_decode_String(arr[1]),
      generatedAtMs: dco_decode_i_64(arr[2]),
      expiresAtMs: dco_decode_i_64(arr[3]),
      candidates: dco_decode_list_recommendation_candidate_dto(arr[4]),
    );
  }

  @protected
  RecommendationSourceDto dco_decode_recommendation_source_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RecommendationSourceDto.values[raw as int];
  }

  @protected
  SongDto dco_decode_song_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return SongDto(
      mediaId: dco_decode_String(arr[0]),
      sourceType: dco_decode_String(arr[1]),
      title: dco_decode_String(arr[2]),
      artists: dco_decode_list_String(arr[3]),
      albumId: dco_decode_opt_String(arr[4]),
      durationMs: dco_decode_opt_box_autoadd_i_32(arr[5]),
      explicit: dco_decode_bool(arr[6]),
      videoOnly: dco_decode_bool(arr[7]),
      available: dco_decode_bool(arr[8]),
      localPath: dco_decode_opt_String(arr[9]),
    );
  }

  @protected
  TrackStatsDto dco_decode_track_stats_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return TrackStatsDto(
      mediaId: dco_decode_String(arr[0]),
      playCount: dco_decode_i_64(arr[1]),
      skipCount: dco_decode_i_64(arr[2]),
      completionCount: dco_decode_i_64(arr[3]),
      impressionCount: dco_decode_i_64(arr[4]),
      liked: dco_decode_bool(arr[5]),
      downloaded: dco_decode_bool(arr[6]),
      localAvailable: dco_decode_bool(arr[7]),
      lastPlayedAtMs: dco_decode_opt_box_autoadd_i_64(arr[8]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  CoreConfig sse_decode_box_autoadd_core_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_core_config(deserializer));
  }

  @protected
  CoreHandle sse_decode_box_autoadd_core_handle(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_core_handle(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  LocalStatsSnapshotDto sse_decode_box_autoadd_local_stats_snapshot_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_local_stats_snapshot_dto(deserializer));
  }

  @protected
  RecommendationEventDto sse_decode_box_autoadd_recommendation_event_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_recommendation_event_dto(deserializer));
  }

  @protected
  RecommendationSnapshotDto sse_decode_box_autoadd_recommendation_snapshot_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_recommendation_snapshot_dto(deserializer));
  }

  @protected
  SongDto sse_decode_box_autoadd_song_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_song_dto(deserializer));
  }

  @protected
  CoreConfig sse_decode_core_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sqlitePath = sse_decode_opt_String(deserializer);
    var var_recommendationServerUrl = sse_decode_opt_String(deserializer);
    return CoreConfig(
        sqlitePath: var_sqlitePath,
        recommendationServerUrl: var_recommendationServerUrl);
  }

  @protected
  CoreHandle sse_decode_core_handle(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sqlitePath = sse_decode_opt_String(deserializer);
    var var_recommendationServerUrl = sse_decode_opt_String(deserializer);
    return CoreHandle(
        sqlitePath: var_sqlitePath,
        recommendationServerUrl: var_recommendationServerUrl);
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RecommendationCandidateDto> sse_decode_list_recommendation_candidate_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RecommendationCandidateDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_recommendation_candidate_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<RecommendationEventDto> sse_decode_list_recommendation_event_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RecommendationEventDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_recommendation_event_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<SongDto> sse_decode_list_song_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SongDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_song_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<TrackStatsDto> sse_decode_list_track_stats_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TrackStatsDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_track_stats_dto(deserializer));
    }
    return ans_;
  }

  @protected
  LocalStatsSnapshotDto sse_decode_local_stats_snapshot_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_generatedAtMs = sse_decode_i_64(deserializer);
    var var_tracks = sse_decode_list_track_stats_dto(deserializer);
    var var_recentMediaIds = sse_decode_list_String(deserializer);
    var var_recentArtistNames = sse_decode_list_String(deserializer);
    return LocalStatsSnapshotDto(
        generatedAtMs: var_generatedAtMs,
        tracks: var_tracks,
        recentMediaIds: var_recentMediaIds,
        recentArtistNames: var_recentArtistNames);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RecommendationSnapshotDto?
      sse_decode_opt_box_autoadd_recommendation_snapshot_dto(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_recommendation_snapshot_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RecommendationCandidateDto sse_decode_recommendation_candidate_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mediaId = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_artists = sse_decode_list_String(deserializer);
    var var_albumId = sse_decode_opt_String(deserializer);
    var var_durationMs = sse_decode_i_32(deserializer);
    var var_source = sse_decode_recommendation_source_dto(deserializer);
    var var_remoteScore = sse_decode_f_32(deserializer);
    var var_reason = sse_decode_opt_String(deserializer);
    return RecommendationCandidateDto(
        mediaId: var_mediaId,
        title: var_title,
        artists: var_artists,
        albumId: var_albumId,
        durationMs: var_durationMs,
        source: var_source,
        remoteScore: var_remoteScore,
        reason: var_reason);
  }

  @protected
  RecommendationEventDto sse_decode_recommendation_event_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_eventId = sse_decode_String(deserializer);
    var var_deviceId = sse_decode_opt_String(deserializer);
    var var_clientClock = sse_decode_i_64(deserializer);
    var var_occurredAtMs = sse_decode_i_64(deserializer);
    var var_kind = sse_decode_recommendation_event_kind_dto(deserializer);
    var var_mediaId = sse_decode_String(deserializer);
    var var_queueId = sse_decode_opt_String(deserializer);
    var var_recommenderSource =
        sse_decode_recommendation_source_dto(deserializer);
    var var_contextJson = sse_decode_String(deserializer);
    var var_payloadJson = sse_decode_String(deserializer);
    return RecommendationEventDto(
        eventId: var_eventId,
        deviceId: var_deviceId,
        clientClock: var_clientClock,
        occurredAtMs: var_occurredAtMs,
        kind: var_kind,
        mediaId: var_mediaId,
        queueId: var_queueId,
        recommenderSource: var_recommenderSource,
        contextJson: var_contextJson,
        payloadJson: var_payloadJson);
  }

  @protected
  RecommendationEventKindDto sse_decode_recommendation_event_kind_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return RecommendationEventKindDto.values[inner];
  }

  @protected
  RecommendationSnapshotDto sse_decode_recommendation_snapshot_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_snapshotId = sse_decode_String(deserializer);
    var var_modelVersion = sse_decode_String(deserializer);
    var var_generatedAtMs = sse_decode_i_64(deserializer);
    var var_expiresAtMs = sse_decode_i_64(deserializer);
    var var_candidates =
        sse_decode_list_recommendation_candidate_dto(deserializer);
    return RecommendationSnapshotDto(
        snapshotId: var_snapshotId,
        modelVersion: var_modelVersion,
        generatedAtMs: var_generatedAtMs,
        expiresAtMs: var_expiresAtMs,
        candidates: var_candidates);
  }

  @protected
  RecommendationSourceDto sse_decode_recommendation_source_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return RecommendationSourceDto.values[inner];
  }

  @protected
  SongDto sse_decode_song_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mediaId = sse_decode_String(deserializer);
    var var_sourceType = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_artists = sse_decode_list_String(deserializer);
    var var_albumId = sse_decode_opt_String(deserializer);
    var var_durationMs = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_explicit = sse_decode_bool(deserializer);
    var var_videoOnly = sse_decode_bool(deserializer);
    var var_available = sse_decode_bool(deserializer);
    var var_localPath = sse_decode_opt_String(deserializer);
    return SongDto(
        mediaId: var_mediaId,
        sourceType: var_sourceType,
        title: var_title,
        artists: var_artists,
        albumId: var_albumId,
        durationMs: var_durationMs,
        explicit: var_explicit,
        videoOnly: var_videoOnly,
        available: var_available,
        localPath: var_localPath);
  }

  @protected
  TrackStatsDto sse_decode_track_stats_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mediaId = sse_decode_String(deserializer);
    var var_playCount = sse_decode_i_64(deserializer);
    var var_skipCount = sse_decode_i_64(deserializer);
    var var_completionCount = sse_decode_i_64(deserializer);
    var var_impressionCount = sse_decode_i_64(deserializer);
    var var_liked = sse_decode_bool(deserializer);
    var var_downloaded = sse_decode_bool(deserializer);
    var var_localAvailable = sse_decode_bool(deserializer);
    var var_lastPlayedAtMs = sse_decode_opt_box_autoadd_i_64(deserializer);
    return TrackStatsDto(
        mediaId: var_mediaId,
        playCount: var_playCount,
        skipCount: var_skipCount,
        completionCount: var_completionCount,
        impressionCount: var_impressionCount,
        liked: var_liked,
        downloaded: var_downloaded,
        localAvailable: var_localAvailable,
        lastPlayedAtMs: var_lastPlayedAtMs);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_core_config(
      CoreConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_core_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_core_handle(
      CoreHandle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_core_handle(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_local_stats_snapshot_dto(
      LocalStatsSnapshotDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_local_stats_snapshot_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_recommendation_event_dto(
      RecommendationEventDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_recommendation_event_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_recommendation_snapshot_dto(
      RecommendationSnapshotDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_recommendation_snapshot_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_song_dto(SongDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_song_dto(self, serializer);
  }

  @protected
  void sse_encode_core_config(CoreConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.sqlitePath, serializer);
    sse_encode_opt_String(self.recommendationServerUrl, serializer);
  }

  @protected
  void sse_encode_core_handle(CoreHandle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.sqlitePath, serializer);
    sse_encode_opt_String(self.recommendationServerUrl, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_recommendation_candidate_dto(
      List<RecommendationCandidateDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_recommendation_candidate_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_recommendation_event_dto(
      List<RecommendationEventDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_recommendation_event_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_song_dto(List<SongDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_song_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_track_stats_dto(
      List<TrackStatsDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_track_stats_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_local_stats_snapshot_dto(
      LocalStatsSnapshotDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.generatedAtMs, serializer);
    sse_encode_list_track_stats_dto(self.tracks, serializer);
    sse_encode_list_String(self.recentMediaIds, serializer);
    sse_encode_list_String(self.recentArtistNames, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_recommendation_snapshot_dto(
      RecommendationSnapshotDto? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_recommendation_snapshot_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_recommendation_candidate_dto(
      RecommendationCandidateDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.mediaId, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_list_String(self.artists, serializer);
    sse_encode_opt_String(self.albumId, serializer);
    sse_encode_i_32(self.durationMs, serializer);
    sse_encode_recommendation_source_dto(self.source, serializer);
    sse_encode_f_32(self.remoteScore, serializer);
    sse_encode_opt_String(self.reason, serializer);
  }

  @protected
  void sse_encode_recommendation_event_dto(
      RecommendationEventDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.eventId, serializer);
    sse_encode_opt_String(self.deviceId, serializer);
    sse_encode_i_64(self.clientClock, serializer);
    sse_encode_i_64(self.occurredAtMs, serializer);
    sse_encode_recommendation_event_kind_dto(self.kind, serializer);
    sse_encode_String(self.mediaId, serializer);
    sse_encode_opt_String(self.queueId, serializer);
    sse_encode_recommendation_source_dto(self.recommenderSource, serializer);
    sse_encode_String(self.contextJson, serializer);
    sse_encode_String(self.payloadJson, serializer);
  }

  @protected
  void sse_encode_recommendation_event_kind_dto(
      RecommendationEventKindDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_recommendation_snapshot_dto(
      RecommendationSnapshotDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.snapshotId, serializer);
    sse_encode_String(self.modelVersion, serializer);
    sse_encode_i_64(self.generatedAtMs, serializer);
    sse_encode_i_64(self.expiresAtMs, serializer);
    sse_encode_list_recommendation_candidate_dto(self.candidates, serializer);
  }

  @protected
  void sse_encode_recommendation_source_dto(
      RecommendationSourceDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_song_dto(SongDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.mediaId, serializer);
    sse_encode_String(self.sourceType, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_list_String(self.artists, serializer);
    sse_encode_opt_String(self.albumId, serializer);
    sse_encode_opt_box_autoadd_i_32(self.durationMs, serializer);
    sse_encode_bool(self.explicit, serializer);
    sse_encode_bool(self.videoOnly, serializer);
    sse_encode_bool(self.available, serializer);
    sse_encode_opt_String(self.localPath, serializer);
  }

  @protected
  void sse_encode_track_stats_dto(
      TrackStatsDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.mediaId, serializer);
    sse_encode_i_64(self.playCount, serializer);
    sse_encode_i_64(self.skipCount, serializer);
    sse_encode_i_64(self.completionCount, serializer);
    sse_encode_i_64(self.impressionCount, serializer);
    sse_encode_bool(self.liked, serializer);
    sse_encode_bool(self.downloaded, serializer);
    sse_encode_bool(self.localAvailable, serializer);
    sse_encode_opt_box_autoadd_i_64(self.lastPlayedAtMs, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
