[package]
name = "sunflower-daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
sunflower-provider = { path = "../provider" }
sunflower-player-interface = { path = "../interface" }
sunflower-daemon-proto = { path = "../proto" }

tracing-subscriber = "0.3"
anyhow = "1.0.58"

