[package]
name = "sunflower-daemon"
version = "0.1.0"
edition = "2021"


[dependencies]
thiserror = "2.0"
tracing = "0.1"
rand = "0.8.5"
rodio = { version = "0.20", features = ["symphonia-all"] }
symphonia = "0.5.4"
async-trait = "0.1.83"
tokio = { version = "1.41.1", features = [
    "macros",
    "rt-multi-thread",
    "net",
    "sync",
    "time",
] }
mio = "1" # I don't know why this is needed, but it if it's not there, tokio's net feature won't compile

sunflower-daemon-proto = { path = "../proto" }

tracing-subscriber = { version = "0.3", features = ["time"] }
anyhow = "1.0.93"

regex = { version = "1.5.5", optional = true }
lofty = { version = "0.21", optional = true }
log = "0.4.22"
time = { version = "0.3.36", features = ["local-offset"] }

[features]

provider-local_file = ["dep:lofty", "dep:regex"]
provider-yt-dlp = []


default = ["provider-local_file"]
all = ["provider-local_file", "provider-yt-dlp"]

daemon-tcp = []
