[package]
name = "sunflower-daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
sunflower-provider = { path = "../provider" }
sunflower-player = { path = "../player", features = ["interface"]}

tracing-subscriber = "0.3"
anyhow = "1.0.58"
clap = { version = "4.5.20", features = ["derive"] }
