name: Rust Format Check

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # with:
        #   token: ${{ secrets.PAT }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check and format code
        run: |
          if ! cargo fmt --all -- --check; then
            cargo fmt --all
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -am "style(ci/cd): Apply automatic formatting"
            git push
          fi
        continue-on-error: true